global:
  name: "consul"
  datacenter: "dc1"
ui:
  enabled: true
  service:
    type: "NodePort"
connectInject:
  enabled: true
controller:
  enabled: true
server:
  replicas: 1
  exposeGossipAndRPCPorts: true
  ports:
    serflan:
      port: 9301
client:
  exposeGossipPorts: true