---
# tasks file for ConsulKV

# https://docs.ansible.com/ansible/latest/collections/community/general/consul_kv_module.html
- name: sync consul kv
  community.general.consul_kv:
    key: "{{ key }}"
    value: "{{ value | to_json }}"
    port: 8500
    host: "{{ server }}" # "127.0.0.1"
    state: "{{ state }}"
    retrieve: yes
    validate_certs: no
