apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consulkv-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  - pods/exec
  - pods/log
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.consul.io
  resources:
  - consulkvs
  - consulkvs/status
  - consulkvs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
