apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: consulkv-operator-leader-election-rolebinding
  namespace: consul
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: consulkv-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: consulkv-operator-controller-manager
  namespace: consul
